spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      uri: mongodb+srv://2023mt03061:GlKc8610IvnNrNtg@cluster0.tzwotuy.mongodb.net/?retryWrites=true&w=majority
      database: ss_db