apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-deployment
  labels:
    app: search
  namespace: ss-search
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search
  template:
    metadata:
      labels:
        app: search
    spec:
      containers:
        - name: search
          image: docker.io/joy1998/ss-search:v2
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: search-service
  namespace: ss-search
spec:
  selector:
    app: search
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
